### PR TITLE
1.0.x

### PR DESCRIPTION
**Pull request by takepon1**
update line 344

### CODE REVIEW

**Comment by dauphine-dev** [comment]
Thank you :-)

**Comment by dauphine-dev** [comment]
May be I have done some thing wrong when I have merged, but I don't see the translation of the line 344.

**Comment by dauphine-dev** [comment]
I have reverted the merge because, I can see changes in others files.

**Comment by takepon1** [comment]
I'm sorry. Probably my mistake. I will attach the file, so please replace it.

     ----- Original Message -----

**Comment by dauphine-dev** [comment]
Great thank you.
Japanese translation updated on Github, it will be available on the next version 1.0.9

**Pull request merged**
